apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: osm
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: strider404/osm-notification-service:latest
          ports:
            - containerPort: 4006
          env:
            - name: MONGO_URI
              value: mongodb://mongo:27017/notificationservice

---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: osm
spec:
  type: ClusterIP
  selector:
    app: notification-service
  ports:
    - protocol: TCP
      port: 4006
      targetPort: 4006
