apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurant-service
  namespace: osm
spec:
  replicas: 2
  selector:
    matchLabels:
      app: restaurant-service
  template:
    metadata:
      labels:
        app: restaurant-service
    spec:
      containers:
        - name: restaurant-service
          image: strider404/osm-restaurant-service:latest
          ports:
            - containerPort: 4002
          env:
            - name: MONGO_URI
              value: mongodb://mongo:27017/restaurantservice

---
apiVersion: v1
kind: Service
metadata:
  name: restaurant-service
  namespace: osm
spec:
  type: ClusterIP
  selector:
    app: restaurant-service
  ports:
    - protocol: TCP
      port: 4002
      targetPort: 4002
